import './globals.css'
import SiteNavBar from "@/components/SiteNavBar";
import SiteFooter from "@/components/SiteFooter";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export async function generateMetadata(){
//   return{
//     title: "Home Page",
//     description:"Assignment -1",
//     keywords:"JSON[0]['keywords'],",
//     openGraph: {
//       images: "JSON[0]['image'],"
//     },
//   }
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <SiteNavBar/>
    {children}
    <SiteFooter/>
    </html>
  )
}
